# Kernel runtime configuration
kernel_settings:
  default_path: "data/kernels/scripts"
  language_settings:
    python:
      version: "3.10"
      file_extensions:
        - ".py"
        - ".ipynb"
      default_packages:
        - "numpy"
        - "pandas"
        - "scikit-learn"
        - "matplotlib"
        - "seaborn"
    r:
      version: "4.0"
      file_extensions:
        - ".r"
        - ".rmd"
      default_packages:
        - "tidyverse"
        - "ggplot2"
        - "caret"

  execution_settings:
    timeout: 3600  # 1 hour in seconds
    max_output_size: 1073741824  # 1GB
    enable_gpu: false
    enable_internet: true
    save_output: true
    save_artifacts: true

  kernel_types:
    notebook:
      metadata_format: "ipynb"
      auto_viz: true
      inline_plots: true

    script:
      metadata_format: "py"
      generate_notebook: false
      output_format: "log"

backup_settings:
  enabled: true
  path: "data/kernels/backups"
  retention_days: 30
  include_data: true
  compress_backups: true

monitoring:
  log_level: "INFO"
  metrics:
    enabled: true
    collect_memory: true
    collect_cpu: true
    collect_gpu: true
  alerts:
    memory_threshold: 0.9  # 90% usage
    execution_time_threshold: 3000  # seconds
    error_notification: true

debugging:
  verbose_output: true
  save_traceback: true
  interactive_debug: false
  error_analysis: true

version_control:
  versioning_enabled: true
  auto_versioning: true
  version_format: "v{major}.{minor}"
  keep_history: true
  max_versions: 10

dependencies:
  package_management:
    pip:
      requirements_file: "requirements.txt"
      allow_pip_install: true
    conda:
      environment_file: "environment.yml"
      allow_conda_install: false

  conflict_resolution:
    strategy: "newer"  # newer, specific, ignore
    pin_versions: true
    allow_upgrades: false

output_handling:
  save_outputs: true
  output_path: "data/kernels/outputs"
  formats:
    - "csv"
    - "json"
    - "png"
    - "html"
  max_files: 100
  compress_outputs: true

metadata:
  required_fields:
    - "title"
    - "language"
    - "kernel_type"
  optional_fields:
    - "description"
    - "dataset_sources"
    - "competition_sources"
  auto_generate:
    - "created_at"
    - "updated_at"
    - "version"
